/*
* generated by Xtext
*/
package info.kwarc.mmt.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import info.kwarc.mmt.services.LFGrammarAccess;

public class LFParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private LFGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens();
	}
	
	@Override
	protected info.kwarc.mmt.parser.antlr.internal.InternalLFParser createParser(XtextTokenStream stream) {
		return new info.kwarc.mmt.parser.antlr.internal.InternalLFParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public LFGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(LFGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
