/*
* generated by Xtext
*/
package info.kwarc.mmt.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import info.kwarc.mmt.services.LFGrammarAccess;

public class LFParser extends AbstractContentAssistParser {
	
	@Inject
	private LFGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected info.kwarc.mmt.ui.contentassist.antlr.internal.InternalLFParser createParser() {
		info.kwarc.mmt.ui.contentassist.antlr.internal.InternalLFParser result = new info.kwarc.mmt.ui.contentassist.antlr.internal.InternalLFParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getModelAccess().getDeclarationsAlternatives_0(), "rule__Model__DeclarationsAlternatives_0");
					put(grammarAccess.getWSAccess().getAlternatives(), "rule__WS__Alternatives");
					put(grammarAccess.getNAMESPACEAccess().getAlternatives_2_0(), "rule__NAMESPACE__Alternatives_2_0");
					put(grammarAccess.getGIDAccess().getAlternatives(), "rule__GID__Alternatives");
					put(grammarAccess.getGIDAccess().getAlternatives_0_0(), "rule__GID__Alternatives_0_0");
					put(grammarAccess.getSOMETHINGAccess().getAlternatives(), "rule__SOMETHING__Alternatives");
					put(grammarAccess.getSOMETHINGAccess().getAlternatives_3_1(), "rule__SOMETHING__Alternatives_3_1");
					put(grammarAccess.getSOMETHING2Access().getAlternatives(), "rule__SOMETHING2__Alternatives");
					put(grammarAccess.getSigOpsAccess().getAlternatives_0(), "rule__SigOps__Alternatives_0");
					put(grammarAccess.getSigConstructAccess().getAlternatives(), "rule__SigConstruct__Alternatives");
					put(grammarAccess.getSigConstructAccess().getTmpAlternatives_3_1_0(), "rule__SigConstruct__TmpAlternatives_3_1_0");
					put(grammarAccess.getClassicSymbolConstructAccess().getAlternatives_2(), "rule__ClassicSymbolConstruct__Alternatives_2");
					put(grammarAccess.getStructConstructAccess().getAlternatives_5(), "rule__StructConstruct__Alternatives_5");
					put(grammarAccess.getTempTypeAccess().getAlternatives(), "rule__TempType__Alternatives");
					put(grammarAccess.getNAMESPACEAccess().getGroup(), "rule__NAMESPACE__Group__0");
					put(grammarAccess.getNAMESPACEAccess().getGroup_0(), "rule__NAMESPACE__Group_0__0");
					put(grammarAccess.getNAMESPACEAccess().getGroup_2(), "rule__NAMESPACE__Group_2__0");
					put(grammarAccess.getURIAccess().getGroup(), "rule__URI__Group__0");
					put(grammarAccess.getURIAccess().getGroup_0(), "rule__URI__Group_0__0");
					put(grammarAccess.getURISTRINGAccess().getGroup(), "rule__URISTRING__Group__0");
					put(grammarAccess.getNamespaceDeclarationAccess().getGroup(), "rule__NamespaceDeclaration__Group__0");
					put(grammarAccess.getNamespaceDeclarationAccess().getGroup_3(), "rule__NamespaceDeclaration__Group_3__0");
					put(grammarAccess.getReadDeclarationAccess().getGroup(), "rule__ReadDeclaration__Group__0");
					put(grammarAccess.getGIDAccess().getGroup_0(), "rule__GID__Group_0__0");
					put(grammarAccess.getGIDAccess().getGroup_0_1(), "rule__GID__Group_0_1__0");
					put(grammarAccess.getGIDAccess().getGroup_1(), "rule__GID__Group_1__0");
					put(grammarAccess.getSOMETHINGAccess().getGroup_3(), "rule__SOMETHING__Group_3__0");
					put(grammarAccess.getSOMETHINGAccess().getGroup_8(), "rule__SOMETHING__Group_8__0");
					put(grammarAccess.getSOMETHING2Access().getGroup_8(), "rule__SOMETHING2__Group_8__0");
					put(grammarAccess.getSigOpsAccess().getGroup(), "rule__SigOps__Group__0");
					put(grammarAccess.getSigOpsAccess().getGroup_0_0(), "rule__SigOps__Group_0_0__0");
					put(grammarAccess.getSigOpsAccess().getGroup_0_1(), "rule__SigOps__Group_0_1__0");
					put(grammarAccess.getSignatureDeclarationAccess().getGroup(), "rule__SignatureDeclaration__Group__0");
					put(grammarAccess.getSignatureDeclarationAccess().getGroup_0(), "rule__SignatureDeclaration__Group_0__0");
					put(grammarAccess.getSigDefinitionsAccess().getGroup(), "rule__SigDefinitions__Group__0");
					put(grammarAccess.getSigDefinitionsAccess().getGroup_3(), "rule__SigDefinitions__Group_3__0");
					put(grammarAccess.getSigDefinitionsAccess().getGroup_4(), "rule__SigDefinitions__Group_4__0");
					put(grammarAccess.getSigConstructAccess().getGroup_3(), "rule__SigConstruct__Group_3__0");
					put(grammarAccess.getClassicSymbolConstructAccess().getGroup(), "rule__ClassicSymbolConstruct__Group__0");
					put(grammarAccess.getIncludeConstructAccess().getGroup(), "rule__IncludeConstruct__Group__0");
					put(grammarAccess.getIncludeConstructAccess().getGroup_4(), "rule__IncludeConstruct__Group_4__0");
					put(grammarAccess.getStructConstructAccess().getGroup(), "rule__StructConstruct__Group__0");
					put(grammarAccess.getIncludeOpsAccess().getGroup(), "rule__IncludeOps__Group__0");
					put(grammarAccess.getViewDeclarationAccess().getGroup(), "rule__ViewDeclaration__Group__0");
					put(grammarAccess.getModelAccess().getDeclarationsAssignment(), "rule__Model__DeclarationsAssignment");
					put(grammarAccess.getJUSTSPACEAccess().getJAssignment(), "rule__JUSTSPACE__JAssignment");
					put(grammarAccess.getNamespaceDeclarationAccess().getNameAssignment_3_0(), "rule__NamespaceDeclaration__NameAssignment_3_0");
					put(grammarAccess.getNamespaceDeclarationAccess().getUriAssignment_4(), "rule__NamespaceDeclaration__UriAssignment_4");
					put(grammarAccess.getReadDeclarationAccess().getFileAssignment_3(), "rule__ReadDeclaration__FileAssignment_3");
					put(grammarAccess.getSignatureDeclarationAccess().getSigNameAssignment_0_3(), "rule__SignatureDeclaration__SigNameAssignment_0_3");
					put(grammarAccess.getSignatureDeclarationAccess().getDefsAssignment_4(), "rule__SignatureDeclaration__DefsAssignment_4");
					put(grammarAccess.getSigDefinitionsAccess().getConstuctsAssignment_2(), "rule__SigDefinitions__ConstuctsAssignment_2");
					put(grammarAccess.getSigDefinitionsAccess().getConstuctsAssignment_3_2(), "rule__SigDefinitions__ConstuctsAssignment_3_2");
					put(grammarAccess.getSigConstructAccess().getTmpAssignment_3_1(), "rule__SigConstruct__TmpAssignment_3_1");
					put(grammarAccess.getClassicSymbolConstructAccess().getSymbNameAssignment_0(), "rule__ClassicSymbolConstruct__SymbNameAssignment_0");
					put(grammarAccess.getIncludeConstructAccess().getNamespaceAssignment_3(), "rule__IncludeConstruct__NamespaceAssignment_3");
					put(grammarAccess.getStructConstructAccess().getStructNameAssignment_3(), "rule__StructConstruct__StructNameAssignment_3");
					put(grammarAccess.getStructConstructAccess().getNamespaceAssignment_7(), "rule__StructConstruct__NamespaceAssignment_7");
					put(grammarAccess.getStructConstructAccess().getIncOptAssignment_9(), "rule__StructConstruct__IncOptAssignment_9");
					put(grammarAccess.getTempTypeAccess().getFullURIAssignment_4(), "rule__TempType__FullURIAssignment_4");
					put(grammarAccess.getViewDeclarationAccess().getViewIDAssignment_3(), "rule__ViewDeclaration__ViewIDAssignment_3");
					put(grammarAccess.getViewDeclarationAccess().getFromAssignment_7(), "rule__ViewDeclaration__FromAssignment_7");
					put(grammarAccess.getViewDeclarationAccess().getToAssignment_11(), "rule__ViewDeclaration__ToAssignment_11");
					put(grammarAccess.getViewDeclarationAccess().getViewDefsAssignment_15(), "rule__ViewDeclaration__ViewDefsAssignment_15");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			info.kwarc.mmt.ui.contentassist.antlr.internal.InternalLFParser typedParser = (info.kwarc.mmt.ui.contentassist.antlr.internal.InternalLFParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] {  };
	}
	
	public LFGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(LFGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
