/*
* generated by Xtext
*/
package info.kwarc.mmt.ui.labeling;

import info.kwarc.mmt.lF.Model;
import info.kwarc.mmt.lF.namespaceDeclaration;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class LFLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public LFLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	String text(Model m) {
		return m.eResource().getURI().lastSegment();
	}
	

	String text(namespaceDeclaration namespace) {
		String uri = namespace.getFullURI()!=null?namespace.getFullURI():namespace.getUri();
		if (namespace.getName() == null)
			return uri;
		else
			return namespace.getName()+": "+uri; 
	}
	
/*
	//Labels and icons can be computed like this:
	
	String text(MyModel ele) {
	  return "my "+ele.getName();
	}
	 
    String image(MyModel ele) {
      return "MyModel.gif";
    }
*/
}
