/*
 * generated by Xtext
 */
package info.kwarc.mmt.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LFExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return info.kwarc.mmt.ui.internal.LFActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return info.kwarc.mmt.ui.internal.LFActivator.getInstance().getInjector("info.kwarc.mmt.LF");
	}
	
}
