/*
* generated by Xtext
*/
package info.kwarc.mmt.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class LFOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
